# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/course.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Course(object):
    def setupUi(self, Course):
        Course.setObjectName("Course")
        Course.resize(595, 160)
        Course.setMinimumSize(QtCore.QSize(595, 160))
        Course.setMaximumSize(QtCore.QSize(595, 160))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui\\icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Course.setWindowIcon(icon)
        self.pushButton = QtWidgets.QPushButton(Course)
        self.pushButton.setGeometry(QtCore.QRect(244, 125, 107, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(Course)
        self.layoutWidget.setGeometry(QtCore.QRect(5, 3, 581, 120))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Course)
        QtCore.QMetaObject.connectSlotsByName(Course)

    def retranslateUi(self, Course):
        _translate = QtCore.QCoreApplication.translate
        Course.setWindowTitle(_translate("Course", "[DLS] Регистрация"))
        self.pushButton.setText(_translate("Course", "Создать"))
        self.label.setText(_translate("Course", "Название:"))
        self.label_2.setText(_translate("Course", "Предмет:"))
        self.label_3.setText(_translate("Course", "Курс института:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Course = QtWidgets.QDialog()
    ui = Ui_Course()
    ui.setupUi(Course)
    Course.show()
    sys.exit(app.exec_())
